In [1]:
import numpy as np

In [9]:
a = np.array([[0,1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
a.shape

(2, 4)

In [11]:
a[1,3]

np.int64(7)

In [12]:
a[1,2] = 8
a

array([[0, 1, 2, 3],
       [4, 5, 8, 7]])

In [13]:
a[0]

array([0, 1, 2, 3])

In [14]:
a[1]

array([4, 5, 8, 7])

In [16]:
b = np.array([3,5])
b

array([3, 5])